# Config file for automatic testing at travis-ci.org

sudo: true
language: python
python:
  - "3.7"
# command to install dependencies
install:
before_script:
  - pip install ray
  - pip install tox-travis
  - pip install coveralls # command to run tests
script: tox
after_success: coveralls
